server:
  port: 8060

logging:
  pattern:
    console: "%-5level | %-25.25logger{25} | %msg%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/v1/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/v1/**