server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

prod:
  rows: 4

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%-5level | %-25.25logger{25} | %msg%n"