spring:
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: msg
    encoding: UTF-8
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/stud
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: "optional:configserver:"


management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always


logging:
  pattern:
    console: "%-5level | %-25.25logger{25} | %msg%n"
#    console: "%-5level | %logger{0} | %msg%n"

my:
  name: saksham1



bcci:
  url : http://localhost:3000
  get:
    all:
      books: /books