logging:
  pattern:
    console: "%-5level | %-25.25logger{25} | %msg%n"

product:
  row: 4

fis:
#  baseUrl: https://jsonplaceholder.typicode.com
  baseUrl: https://httpstat.us/500
  postFileUri: /posts
  books: /posts/2

