spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/sms
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: ALWAYS
    # disabled job run at startup
    job:
      enabled: false

