server:
  port: 8080


spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://127.0.0.1:5000
        registration:
          boat:
            client-id: client
            client-secret: secret
            client-name: Login with mock auth server
            provider: spring
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: profile
            authorization-grant-type: authorization_code
#            client-authentication-method=client_secret_post


logging:
  pattern:
    console: "%-5level | %msg%n"
#    console: "%-5level | %-25.25logger{25} | %msg%n"

#spring.security.oauth2.client.registration.client.client-authentication-method=client_secret_basic